### ISSUE TITLE
Battery spark integration not working

### ISSUE THREAD

**Issue by minimenchmuncher** [Goles/Battery#20]
I see a blank instead of the bar provided by `spark`, after just installing both `spark` and `battery` using homebrew (love the tool- great with tmux, by the way!)

![screen shot 2015-05-09 at 10 07 23 am](https://cloud.githubusercontent.com/assets/3420931/7550514/4902d452-f633-11e4-88d5-436d3e698aa0.png)

I think that the issue is in line 128:
```bash
  GRAPH=$(spark 0 ${BATTERY_STATUS} 100 | awk '{print substr($0,4,3)}')
```

Broken down, I see that
```bash
spark 0 ${BATTERY_STATUS} 100
```
looks like
![screen shot 2015-05-09 at 10 11 38 am](https://cloud.githubusercontent.com/assets/3420931/7550538/d09599f4-f633-11e4-800a-a8f21183ce0f.png)

So shouldn't the awk substr part of this look like:
```bash
GRAPH=$(spark 0 ${BATTERY_STATUS} 100 | awk '{print substr($0,2,1)}')
```

When I made this change, the `battery` command yields the following:
![screen shot 2015-05-09 at 10 15 39 am](https://cloud.githubusercontent.com/assets/3420931/7550557/79a58cc0-f634-11e4-98e3-0e1feff36078.png)

This seems to work for me. It's entirely possible that the `awk '{print substr($0, 4, 3)}'` part worked with an earlier version of spark, not sure (I'm new to both tools). I'm happy to push this change to a new branch - thoughts?

**Comment by Goles** [comment]
It would be nice to have a PR to test.

What's your current spark version?

Thanks :100:

**Comment by Goles** [comment]
Just checked spark and the current version of the project is 1.0.1. It's been like that for a while, so maybe there's something else going on here.

Maybe you could echo the input that you're passing to awk :)

**Comment by minimenchmuncher** [comment]
I'm definitely using spark 1.0.1, which looks like it hasn't substantially changed in a while.

Here's a couple of screenshots of what's going on.
With `BATTERY_STATUS` = 97, the commands in order are
```bash
echo $BATTERY_STATUS #verify the value of the variable
echo $(spark 0 ${BATTERY_STATUS} 100) # look at the input to awk
echo $(spark 0 ${BATTERY_STATUS} 100 | awk '{print substr($0,2,1)}') # the command that seems to work for me
echo $(spark 0 ${BATTERY_STATUS} 100 | awk '{print substr($0,4,3)}') # the command that doesn't seem to work
```

The results are below:
![screen shot 2015-05-10 at 5 12 39 pm](https://cloud.githubusercontent.com/assets/3420931/7556272/cff01e84-f737-11e4-9f97-8c6e6997372f.png)

**Comment by jsatk** [comment]
@minimenchmuncher I'm current experiencing this exact issue. Why did you close this? Was there a fix?

**Comment by Goles** [comment]
Hey @jsatk It's been working fine for most people I know. What OS are you using?

**Comment by jsatk** [comment]
My apologies. I should've followed up. I got it working. It was a configuration issue on my end. Thanks for the great tool.

**Comment by Goles** [comment]
@jsatk no problem. I'm glad it's working for you!
