### ISSUE TITLE
Linux support possibility

### ISSUE THREAD

**Issue by minimenchmuncher** [Goles/Battery#21]
I recently started using a laptop running Ubuntu and I was wondering if there were any plans for adding Linux support for Battery (I really like the output it generates, am already used to it, etc.)

I had been playing around with the script a bit, and I think `battery_external_connected()` and `run_battery()` could be modified, switching on the value of `$(uname -s)` and using UPower (I'm pretty sure it's fairly universal for linuxes). Another possibility would be to modify the `battery_info()` to switch on the value of `$(uname -s)`, and for linux it would run `upower` and reformat the output instead of running `ioreg`. Thoughts?

**Comment by Goles** [comment]
We could totally make it compatible with Linux, I can't really test for compatibility or anything. I'm open for PRs, so if you want to take the discussion for Linux support to a PR, I totally encourage it :+1:

**Comment by minimenchmuncher** [comment]
I forked the repo if you want to take a look at it there (I don't have permission to push to a new branch here).

**Comment by Goles** [comment]
Even if you can't push to a new branch here, you can still issue a pull request :+1: 

I think it's better if you Pull Request and we iterate over that, what do you think?

**Comment by Goles** [comment]
@minimenchmuncher do you want me to close this PR?

**Comment by minimenchmuncher** [comment]
Maybe not quite yet? I'm working off of @gerep 's work right now, adding back in `upower` as an option, allowing for exotic battery paths, etc. A version of it is up on [minimenchmuncher/battery](https://github.com/minimenchmuncher/Battery/blob/master/battery) but it's not ready to merge yet.

**Comment by Goles** [comment]
Hey @minimenchmuncher , I thought I had made this comment in a very old PR that was open. Disregard my previous comment :)
