### ISSUE TITLE
Sha1 in brew is deprecated

### ISSUE THREAD

**Issue by gabamnml** [Goles/Battery#28]
Instead of using Sha1 in battery, now we must use Sha256
![screen shot 2016-07-30 at 03 09 22](https://cloud.githubusercontent.com/assets/379450/17268802/8e21087a-5603-11e6-80e1-ce7a8e9adda0.png)

Regards!

**Comment by Goles** [comment]
Nice catch! On the beach today, will update when back :)

**Comment by Goles** [comment]
I merged a PR to fix this into our tap's repo, thanks for reporting @gabamnml
