### ISSUE TITLE
Remove emoji ?

### ISSUE THREAD

**Issue by alextrastero** [Goles/Battery#29]
Hi, first of all thanks for this, is there any chance I can remove the "plugged in" emoji?

**Comment by Goles** [comment]
I think you can try running battery with `-a ''` . That's to pass an empty ascii character. Of it doesn't work, I'll consider the feature :)

**Comment by alextrastero** [comment]
<img width="132" alt="screen shot 2016-10-19 at 18 39 55" src="https://cloud.githubusercontent.com/assets/4152819/19528242/809f38ee-962b-11e6-8908-aef70f6b2b18.png">

**Comment by Goles** [comment]
Hey @alextrastero there's an open PR to do this that never made it (#27) do you want to take a look at it and see if it solves the issue for you?

**Comment by alextrastero** [comment]
@Goles thanks for the reply, i'm a complete newbie when it comes to shell scripts. Is it as simple as editing the `/usr/local/bin/battery` file ?? Do I have to source it after?? Thanks again

**Comment by abkahrs** [comment]
@alextrastero yes to both. the file can be replaced with https://github.com/frmendes/Battery/blob/5e24c3fb531b21a7dd71b2c58aca32b1d9d26783/battery

**Comment by ismay** [comment]
Has this been published to homebrew? I don't know if packages even have to be manually published to homebrew, but the `-e` flag only results in `Invalid option: -e`  for me, even though I did a fresh install.
