### ISSUE TITLE
Compatibility with zsh

### ISSUE THREAD

**Issue by grenmester** [Goles/Battery#32]
I tried using `battery` in `zsh` but it was very glitchy and did not work as expected. The printout gets partially cut off in the middle and messes up the rest of the prompt. It also seems as if there is a large chunk of trailing whitespace that comes after the output.

I tried using battery in `bash` and I was able to get it to work. I am not sure what the issue is with `zsh` but I would love to have it fixed so I can use it in my `.zshrc`!

**Comment by Goles** [comment]
Hey!

You on macOS?

**Comment by grenmester** [comment]
Yes, I am currently on macOS Sierra 10.12.2.

**Comment by Goles** [comment]
Interesting, I'm on 10.11.6 and it's running in ZSH without any issues. Could you post a screenshot of what you see? What terminal application are you using?

**Comment by grenmester** [comment]
I am using iTerm2.
![image](https://cloud.githubusercontent.com/assets/13500910/23776056/ba7fda90-04e0-11e7-92e0-593fa0542ee2.png)

**Comment by Goles** [comment]
Is this pure zsh ? or you using tmux with it?

It's kinda' weird, is UTF-8 enabled for you? if you're in tmux, have you tried to do `tmux -u` when you run it to enable UTF-8 support?

**Comment by grenmester** [comment]
This is pure `zsh` and UTF-8 is enabled.

**Comment by grenmester** [comment]
I have looked at the code and narrowed down the issue to line 155. It seems that `"\e[0;%sm%s %s \e[m\n"` is somehow inserting an extra tab or something when I have it in my `zsh` prompt. Specifically, when I add just the `"\e[0;%sm%s"` part to my `zsh` prompt, the tab appears. I also have `setopt prompt_subst` in my `.zshrc` if that helps.

**Comment by Goles** [comment]
That's very helpful. Do you mind issuing a PR?

**Comment by grenmester** [comment]
Sure, as soon as I actually fix the bug since I haven't actually figured out how to fix it 😛 .

**Comment by Goles** [comment]
I understand @grenmester , I'm not in Sierra so that limits my ability to test this. Have you tried in `Terminal.app`? just curious if you see the same issue.

**Comment by grenmester** [comment]
When I use in for my left hand prompt, it works fine. However, when I use it for my right prompt, it gives that weird extra space.

**Comment by grenmester** [comment]
I was able to fix this by using the format that the zsh prompt uses for colors. I am unable to make a pull request though as I realized that the version of `battery` I was editing was an older version that is on the brew tap. Once the current version is fixed I should be able to pull request and add that zsh option.

**Comment by STJEREM** [comment]
I had to add escape characters:

`printf "%%{\e[0;%sm%%}%s %s%%{\e[0m%%}\n" "$COLOR"  "$BATTERY_STATUS%%" "$GRAPH"`
