### ISSUE TITLE
Brew formula version 1.4?

### ISSUE THREAD

**Issue by grenmester** [Goles/Battery#33]
So I realized that the brew formula is not currently up-to-date with this repository so that should probably be fixed. I was also wondering why `battery` had to be in a separate brew tap. In addition, when I tried running this script, I came across a syntax error:

```
battery: line 70: syntax error near unexpected token `<'
battery: line 70: `                done < <(ioreg -n AppleSmartBattery -r | grep -o '"[^"]*" = [^ ]*' | sed -e 's/= //g' -e 's/"//g' | sort)'
```

**Comment by grenmester** [comment]
Just realized that my bash was acting weird. However, it would still be nice to have a version 1.4 so options like -e and -z can be added.

**Comment by austinmcconnell** [comment]
I'll second that. With homebrew being such a popular package manager for mac, it would be great to get the latest version `brew install`-able

**Comment by Goles** [comment]
Hey, just posting here because I'll be working on getting this done this weekend. I'll try to do some cleanup and some PR triage this Saturday.

Thanks for everyone's input.
